export const LOADING = 'LOADING'
export const ERROR = 'ERROR'

export const LOG_REQUEST = 'LOG_REQUEST'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST' 

export const GET_PRODUCTS_LIMIT = 'GET_PRODUCTS_LIMIT'
export const GET_PRODUCT = 'GET_PRODUCT'

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'
export const ADD_SHIPPING_OPTION = 'ADD_SHIPPING_OPTION'
export const ADD_PAYMENT_OPTION = 'ADD_PAYMENT_OPTION'
export const PAYMENT_COMPLETED = 'PAYMENT_COMPLETED'