export const LOG_REQUEST = 'LOG_REQUEST'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST' 

export const GET_PRODUCTS_LIMIT = 'GET_PRODUCTS_LIMIT'
export const GET_PRODUCT = 'GET_PRODUCT'